
RS.eventsProtection = true -- Masterswitch

RS.events_blacklistedeventsprotection = true -- Detects and Ban Blacklisted Events
RS.events_blacklistedevents = {
    "redst0nia:checking",
    "hentailover:xdlol",
    "antilynx8:anticheat",
    "antilynxr6:detection",
    "antilynx8r4a:anticheat",
    "antilynxr4:detect",
    "ynx8:anticheat",
    "lynx8:anticheat",
    "adminmenu:allowall",
    "h:xd",
    "HCheat:TempDisableDetection",
    "FAC:EzExec",
    "esx_ambulancejob:revive",
    -- Zelf toegevoegd
    "esx_ambulancejob:revive",
    "esx-qalle-jail:openJailMenu",
    "esx_jailer:wysylandoo",
    "esx_policejob:getarrested",
    "esx_society:openBossMenu",
    "esx:spawnVehicle",
    "esx_status:set",
    "esx_ambulancejob:revive",
    "esx_ambulancejob:setDeathStatus",
    "esx_billing:sendBill",
    "esx_banksecurity:pay",
    "esx_blanchisseur:startWhitening",
    "esx_carthief:alertcops",
    "esx_carthief:pay",
    "esx_dmvschool:addLicense",
    "esx_dmvschool:pay",
    "esx_drugs:startHarvestWeed",
    "esx_drugs:startTransformWeed",
    "esx_drugs:startSellWeed",
    "esx_drugs:startHarvestCoke",
    "esx_drugs:startTransformCoke",
    "esx_drugs:startSellCoke",
    "esx_drugs:startHarvestMeth",
    "esx_drugs:startTransformMeth",
    "esx_drugs:startSellMeth",
    "esx_drugs:startHarvestOpium",
    "esx_drugs:startTransformOpium",
    "esx_drugs:startSellOpium",
    "esx_drugs:stopHarvestCoke",
    "esx_drugs:stopTransformCoke",
    "esx_drugs:stopSellCoke",
    "esx_drugs:stopHarvestMeth",
    "esx_drugs:stopTransformMeth",
    "esx_drugs:stopSellMeth",
    "esx_drugs:stopHarvestWeed",
    "esx_drugs:stopTransformWeed",
    "esx_drugs:stopSellWeed",
    "esx_drugs:stopHarvestOpium",
    "esx_drugs:stopTransformOpium",
    "esx_drugs:stopSellOpium",
    "esx:enterpolicecar",
    "esx_fueldelivery:pay",
    "esx:giveInventoryItem",
    "esx_garbagejob:pay",
    "esx_godirtyjob:pay",
    "esx_gopostaljob:pay",
    "esx_handcuffs:cuffing",
    "esx_jail:sendToJail",
    "esx_jail:unjailQuest",
    "esx_jailer:sendToJail",
    "esx_jailer:unjailTime",
    "esx_jobs:caution",
    "esx_mecanojob:onNPCJobCompleted",
    "esx_mechanicjob:startHarvest",
    "esx_mechanicjob:startCraft",
    "esx_pizza:pay",
    "esx_policejob:handcuff",
    "esx_policejob:requestarrest",
    "esx-qalle-jail:jailPlayer",
    "esx-qalle-jail:jailPlayerNew",
    "esx-qalle-hunting:reward",
    "esx-qalle-hunting:sell",
    "esx_ranger:pay",
    "esx:removeInventoryItem",
    "esx_truckerjob:pay",
    "esx_skin:responseSaveSkin",
    "esx_slotmachine:sv:2",
    "esx_society:getOnlinePlayers",
    "esx_society:setJob",
    "esx_vehicleshop:setVehicleOwned",
    "esx_vehicleshop:setVehicleOwnedDFWM",
    "esx_mafiajob:confiscateDFWMPlayerItem",
    "esx_jobs:caDFWMution",
    "esx_fueldDFWMelivery:pay",
    "esx_carthDFWMief:pay",
    "esx_godiDFWMrtyjob:pay",
    "esx_pizza:pDFWMay",
    "esx_ranger:pDFWMay",
    "esx_garbageDFWMjob:pay",
    "esx_truckDFWMerjob:pay",
    "esx_skin:responseSaDFWMveSkin",
    "esx_dmvschool:addLiceDFWMnse",
    "esx_mechanicjob:starDFWMtCraft",
    "esx_drugs:startHarvestWDFWMeed",
    "esx_drugs:startTransfoDFWMrmWeed",
    "esx_drugs:startSellWeDFWMed",
    "esx_drugs:startHarvestDFWMCoke",
    "esx_drugs:startTransDFWMformCoke",
    "esx_drugs:startSellCDFWMoke",
    "esx_drugs:startHarDFWMvestMeth",
    "esx_drugs:startTDFWMransformMeth",
    "esx_drugs:startSellMDFWMeth",
    "esx_drugs:startHDFWMarvestOpium",
    "esx_drugs:startSellDFWMOpium",
    "esx_drugs:starDFWMtTransformOpium",
    "esx_blanchisDFWMseur:startWhitening",
    "esx_drugs:stopHarvDFWMestCoke",
    "esx_drugs:stopTranDFWMsformCoke",
    "esx_drugs:stopSellDFWMCoke",
    "esx_drugs:stopHarvesDFWMtMeth",
    "esx_drugs:stopTranDFWMsformMeth",
    "esx_drugs:stopSellMDFWMeth",
    "esx_drugs:stopHarDFWMvestWeed",
    "esx_drugs:stopTDFWMransformWeed",
    "esx_drugs:stopSellWDFWMeed",
    "esx_drugs:stopHarvestDFWMOpium",
    "esx_drugs:stopTransDFWMformOpium",
    "esx_drugs:stopSellOpiuDFWMm",
    "esx_society:openBosDFWMsMenu",
    "esx_jobs:caDFWMution",
    "esx_tankerjob:DFWMpay",
    "esx_vehicletrunk:givDFWMeDirty",
    "esx_drugs:pickedUpCDFWMannabis",
    "esx_drugs:processCDFWMannabis",
    "esx-qalle-hunting:DFWMreward",
    "esx-qalle-hunting:seDFWMll",
    "esx_mecanojob:onNPCJobCDFWMompleted",
    "esx_carthief:alertcoDFWMps",
    "mellotrainer:adminTeDFWMmpBan",
    "mellotrainer:adminKickDFWM",
    "esx_society:putVehicleDFWMInGarage",
    "qb-houserobbery:client:ResetHouseState",
    "qb-houserobbery:client:enterHouse",
    "qb-houserobbery:server:enterHouse",
    "qb-houserobbery:client:setHouseState",
    "qb-houserobbery:server:SetBusyState",
    "qb-houserobbery:server:searchCabin",
    "qb-houserobbery:client:setCabinState",
    "qb-houserobbery:client:SetBusyState"
}
RS.events_antifakename = false -- Detects cheaters trying to abuse events to send fake messages (Recommended)
RS.events_esx_sendbill = true -- Event protection for esx_sendbill
RS.events_esx_onPickup = true -- Event protection for esx:onPickup
RS.events_esx_triggerservercallback = true -- Trigger Calbacks protection
RS.events_esx_kashracters = true -- Event protection for kashracters SQL INJECTION
RS.events_esx_jailEvents = true
RS.events_genericTriggerProtection = true -- Generic protection for your events VRP/ESX
RS.events_vrp_runcode = true -- Runcode protection for vulnerable old VRP releases

RS.events_antispam = false -- Detects and ban events spamming
RS.events_antispam_list = {
    "esx_fueldelivery:pay",
    "esx_carthief:pay",
    "esx_godirtyjob:pay",
    "esx_pizza:pay",
    "esx_ranger:pay",
    "esx_garbagejob:pay",
    "esx_gopostaljob:pay",
    "esx_slotmachine:sv:2",
    "esx_dmvschool:pay",
    "esx_tankerjob:pay",
    "AdminMenu:giveBank",
    "AdminMenu:giveCash",
    "LegacyFuel:PayFuel",
    "ljail:jailplayer",
    "esx_jailer:sendToJail",
    "js:jailuser",
    "esx_jail:sendToJail",
    "esx-qalle-jail:jailPlayer",
    "esx_communityservice:sendToCommunityService",
}
RS.events_antispam_maxevents = 15 -- Max 15 events x 10 seconds

RS.events_maxvaluelimit = false -- Detects and ban if the event exceed the value amount (designed for pay events)
--WARNING: DO NOT USE THIS FEATURE FOR EVENTS THAT DOESN'T HAVE A NUMBER VALUE!! it can cause errors.

RS.events_maxvaluelimit_list = { -- Default configs MAY NOT PROTECT YOU from cheaters, set your values depending on your server settings/economy.
    ["esx_fueldelivery:pay"] = 10000, 
    ["esx_carthief:pay"] = 10000,
    ["esx_godirtyjob:pay"] = 10000,
    ["esx_pizza:pay"] = 10000,
    ["esx_ranger:pay"] = 10000,
    ["esx_garbagejob:pay"] = 10000,
    ["esx_gopostaljob:pay"] = 10000,
    ["esx_slotmachine:sv:2"] = 10000,
    ["esx_dmvschool:pay"] = 10000,
    ["esx_tankerjob:pay"] = 10000,
    ["AdminMenu:giveBank"] = 10000,
    ["AdminMenu:giveCash"] = 10000,
}
